services:
  db:
    image: postgres
    restart: always
    shm_size: 1gb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
