/*
 * This source file was generated by the Gradle 'init' task
 */
package org.amts;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {
    @Test void contextLoads() {
    }
}
